#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SiriDB")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Inserttbl_user(tbl_user instance);
  partial void Updatetbl_user(tbl_user instance);
  partial void Deletetbl_user(tbl_user instance);
  partial void Inserttbl_sire_line(tbl_sire_line instance);
  partial void Updatetbl_sire_line(tbl_sire_line instance);
  partial void Deletetbl_sire_line(tbl_sire_line instance);
  partial void Inserttbl_siri_station(tbl_siri_station instance);
  partial void Updatetbl_siri_station(tbl_siri_station instance);
  partial void Deletetbl_siri_station(tbl_siri_station instance);
  partial void Inserttbl_parking(tbl_parking instance);
  partial void Updatetbl_parking(tbl_parking instance);
  partial void Deletetbl_parking(tbl_parking instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiriDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tbl_user> tbl_users
	{
		get
		{
			return this.GetTable<tbl_user>();
		}
	}
	
	public System.Data.Linq.Table<tbl_sire_line> tbl_sire_lines
	{
		get
		{
			return this.GetTable<tbl_sire_line>();
		}
	}
	
	public System.Data.Linq.Table<tbl_siri_station> tbl_siri_stations
	{
		get
		{
			return this.GetTable<tbl_siri_station>();
		}
	}
	
	public System.Data.Linq.Table<tbl_operator> tbl_operators
	{
		get
		{
			return this.GetTable<tbl_operator>();
		}
	}
	
	public System.Data.Linq.Table<tbl_parking> tbl_parkings
	{
		get
		{
			return this.GetTable<tbl_parking>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_users")]
public partial class tbl_user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _userName;
	
	private string _password;
	
	private System.Nullable<bool> _status;
	
	private System.Nullable<bool> _admin;
	
	private System.Nullable<System.DateTime> _dater;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnstatusChanging(System.Nullable<bool> value);
    partial void OnstatusChanged();
    partial void OnadminChanging(System.Nullable<bool> value);
    partial void OnadminChanged();
    partial void OndaterChanging(System.Nullable<System.DateTime> value);
    partial void OndaterChanged();
    #endregion
	
	public tbl_user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="NVarChar(50)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Bit")]
	public System.Nullable<bool> status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="Bit")]
	public System.Nullable<bool> admin
	{
		get
		{
			return this._admin;
		}
		set
		{
			if ((this._admin != value))
			{
				this.OnadminChanging(value);
				this.SendPropertyChanging();
				this._admin = value;
				this.SendPropertyChanged("admin");
				this.OnadminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dater", DbType="DateTime")]
	public System.Nullable<System.DateTime> dater
	{
		get
		{
			return this._dater;
		}
		set
		{
			if ((this._dater != value))
			{
				this.OndaterChanging(value);
				this.SendPropertyChanging();
				this._dater = value;
				this.SendPropertyChanged("dater");
				this.OndaterChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_sire_lines")]
public partial class tbl_sire_line : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _LineID;
	
	private string _StationID;
	
	private System.Nullable<System.DateTime> _UpdateTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnLineIDChanging(string value);
    partial void OnLineIDChanged();
    partial void OnStationIDChanging(string value);
    partial void OnStationIDChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    #endregion
	
	public tbl_sire_line()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineID", DbType="NVarChar(50)")]
	public string LineID
	{
		get
		{
			return this._LineID;
		}
		set
		{
			if ((this._LineID != value))
			{
				this.OnLineIDChanging(value);
				this.SendPropertyChanging();
				this._LineID = value;
				this.SendPropertyChanged("LineID");
				this.OnLineIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(50)")]
	public string StationID
	{
		get
		{
			return this._StationID;
		}
		set
		{
			if ((this._StationID != value))
			{
				this.OnStationIDChanging(value);
				this.SendPropertyChanging();
				this._StationID = value;
				this.SendPropertyChanged("StationID");
				this.OnStationIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateTime
	{
		get
		{
			return this._UpdateTime;
		}
		set
		{
			if ((this._UpdateTime != value))
			{
				this.OnUpdateTimeChanging(value);
				this.SendPropertyChanging();
				this._UpdateTime = value;
				this.SendPropertyChanged("UpdateTime");
				this.OnUpdateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_siri_stations")]
public partial class tbl_siri_station : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _StationID;
	
	private System.Nullable<System.DateTime> _UpdateTime;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStationIDChanging(string value);
    partial void OnStationIDChanged();
    partial void OnUpdateTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdateTimeChanged();
    #endregion
	
	public tbl_siri_station()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="NVarChar(50)")]
	public string StationID
	{
		get
		{
			return this._StationID;
		}
		set
		{
			if ((this._StationID != value))
			{
				this.OnStationIDChanging(value);
				this.SendPropertyChanging();
				this._StationID = value;
				this.SendPropertyChanged("StationID");
				this.OnStationIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdateTime", DbType="DateTime")]
	public System.Nullable<System.DateTime> UpdateTime
	{
		get
		{
			return this._UpdateTime;
		}
		set
		{
			if ((this._UpdateTime != value))
			{
				this.OnUpdateTimeChanging(value);
				this.SendPropertyChanging();
				this._UpdateTime = value;
				this.SendPropertyChanged("UpdateTime");
				this.OnUpdateTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_operators")]
public partial class tbl_operator
{
	
	private int _ID;
	
	private string _operator_id;
	
	private string _operator_name;
	
	private System.Nullable<System.DateTime> _dater;
	
	public tbl_operator()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this._ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_id", DbType="NChar(10)")]
	public string operator_id
	{
		get
		{
			return this._operator_id;
		}
		set
		{
			if ((this._operator_id != value))
			{
				this._operator_id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_name", DbType="NVarChar(50)")]
	public string operator_name
	{
		get
		{
			return this._operator_name;
		}
		set
		{
			if ((this._operator_name != value))
			{
				this._operator_name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dater", DbType="DateTime")]
	public System.Nullable<System.DateTime> dater
	{
		get
		{
			return this._dater;
		}
		set
		{
			if ((this._dater != value))
			{
				this._dater = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_parkings")]
public partial class tbl_parking : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _parking_id;
	
	private string _parking_name;
	
	private string _parking_coordinates;
	
	private System.Nullable<System.DateTime> _dater;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onparking_idChanging(System.Nullable<int> value);
    partial void Onparking_idChanged();
    partial void Onparking_nameChanging(string value);
    partial void Onparking_nameChanged();
    partial void Onparking_coordinatesChanging(string value);
    partial void Onparking_coordinatesChanged();
    partial void OndaterChanging(System.Nullable<System.DateTime> value);
    partial void OndaterChanged();
    #endregion
	
	public tbl_parking()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parking_id", DbType="Int")]
	public System.Nullable<int> parking_id
	{
		get
		{
			return this._parking_id;
		}
		set
		{
			if ((this._parking_id != value))
			{
				this.Onparking_idChanging(value);
				this.SendPropertyChanging();
				this._parking_id = value;
				this.SendPropertyChanged("parking_id");
				this.Onparking_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parking_name", DbType="NVarChar(50)")]
	public string parking_name
	{
		get
		{
			return this._parking_name;
		}
		set
		{
			if ((this._parking_name != value))
			{
				this.Onparking_nameChanging(value);
				this.SendPropertyChanging();
				this._parking_name = value;
				this.SendPropertyChanged("parking_name");
				this.Onparking_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parking_coordinates", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string parking_coordinates
	{
		get
		{
			return this._parking_coordinates;
		}
		set
		{
			if ((this._parking_coordinates != value))
			{
				this.Onparking_coordinatesChanging(value);
				this.SendPropertyChanging();
				this._parking_coordinates = value;
				this.SendPropertyChanged("parking_coordinates");
				this.Onparking_coordinatesChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dater", DbType="DateTime")]
	public System.Nullable<System.DateTime> dater
	{
		get
		{
			return this._dater;
		}
		set
		{
			if ((this._dater != value))
			{
				this.OndaterChanging(value);
				this.SendPropertyChanging();
				this._dater = value;
				this.SendPropertyChanged("dater");
				this.OndaterChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
