//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TestWebServices.ituranWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service3Soap", Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class Service3 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetVehicleMileageOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetVehicleMileageExtendedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllVehicleMileageOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateVehicleTripRoute_BCityOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateVehicleTripRouteOperationCompleted;
        
        private System.Threading.SendOrPostCallback WakeupOperationCompleted;
        
        private System.Threading.SendOrPostCallback SetDebugModeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlatformDataExtentededOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPlatformDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPlatformsDataShortenedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllPlatformsDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUpdateKeyboardPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUpdateOdometerOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckCommandResultOperationCompleted;
        
        private System.Threading.SendOrPostCallback RevGeoCodingOperationCompleted;
        
        private System.Threading.SendOrPostCallback RevGeoCodingExactOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service3() {
            this.Url = global::TestWebServices.Properties.Settings.Default.TestWebServices_com_ituran_www_Service3;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetVehicleMileageCompletedEventHandler GetVehicleMileageCompleted;
        
        /// <remarks/>
        public event GetVehicleMileageExtendedCompletedEventHandler GetVehicleMileageExtendedCompleted;
        
        /// <remarks/>
        public event GetAllVehicleMileageCompletedEventHandler GetAllVehicleMileageCompleted;
        
        /// <remarks/>
        public event UpdateVehicleTripRoute_BCityCompletedEventHandler UpdateVehicleTripRoute_BCityCompleted;
        
        /// <remarks/>
        public event UpdateVehicleTripRouteCompletedEventHandler UpdateVehicleTripRouteCompleted;
        
        /// <remarks/>
        public event WakeupCompletedEventHandler WakeupCompleted;
        
        /// <remarks/>
        public event SetDebugModeCompletedEventHandler SetDebugModeCompleted;
        
        /// <remarks/>
        public event GetPlatformDataExtentededCompletedEventHandler GetPlatformDataExtentededCompleted;
        
        /// <remarks/>
        public event GetPlatformDataCompletedEventHandler GetPlatformDataCompleted;
        
        /// <remarks/>
        public event GetAllPlatformsDataShortenedCompletedEventHandler GetAllPlatformsDataShortenedCompleted;
        
        /// <remarks/>
        public event GetAllPlatformsDataCompletedEventHandler GetAllPlatformsDataCompleted;
        
        /// <remarks/>
        public event SendUpdateKeyboardPasswordCompletedEventHandler SendUpdateKeyboardPasswordCompleted;
        
        /// <remarks/>
        public event SendUpdateOdometerCompletedEventHandler SendUpdateOdometerCompleted;
        
        /// <remarks/>
        public event CheckCommandResultCompletedEventHandler CheckCommandResultCompleted;
        
        /// <remarks/>
        public event RevGeoCodingCompletedEventHandler RevGeoCodingCompleted;
        
        /// <remarks/>
        public event RevGeoCodingExactCompletedEventHandler RevGeoCodingExactCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetVehicleMileage", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VehiceMileage GetVehicleMileage(string Plate, string LocTime, string UserName, string Password) {
            object[] results = this.Invoke("GetVehicleMileage", new object[] {
                        Plate,
                        LocTime,
                        UserName,
                        Password});
            return ((VehiceMileage)(results[0]));
        }
        
        /// <remarks/>
        public void GetVehicleMileageAsync(string Plate, string LocTime, string UserName, string Password) {
            this.GetVehicleMileageAsync(Plate, LocTime, UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetVehicleMileageAsync(string Plate, string LocTime, string UserName, string Password, object userState) {
            if ((this.GetVehicleMileageOperationCompleted == null)) {
                this.GetVehicleMileageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVehicleMileageOperationCompleted);
            }
            this.InvokeAsync("GetVehicleMileage", new object[] {
                        Plate,
                        LocTime,
                        UserName,
                        Password}, this.GetVehicleMileageOperationCompleted, userState);
        }
        
        private void OnGetVehicleMileageOperationCompleted(object arg) {
            if ((this.GetVehicleMileageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVehicleMileageCompleted(this, new GetVehicleMileageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetVehicleMileageExtended", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VehiceMileage GetVehicleMileageExtended(string Plate, string LocTime, string UserName, string Password, string ShowMileageInMeters) {
            object[] results = this.Invoke("GetVehicleMileageExtended", new object[] {
                        Plate,
                        LocTime,
                        UserName,
                        Password,
                        ShowMileageInMeters});
            return ((VehiceMileage)(results[0]));
        }
        
        /// <remarks/>
        public void GetVehicleMileageExtendedAsync(string Plate, string LocTime, string UserName, string Password, string ShowMileageInMeters) {
            this.GetVehicleMileageExtendedAsync(Plate, LocTime, UserName, Password, ShowMileageInMeters, null);
        }
        
        /// <remarks/>
        public void GetVehicleMileageExtendedAsync(string Plate, string LocTime, string UserName, string Password, string ShowMileageInMeters, object userState) {
            if ((this.GetVehicleMileageExtendedOperationCompleted == null)) {
                this.GetVehicleMileageExtendedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetVehicleMileageExtendedOperationCompleted);
            }
            this.InvokeAsync("GetVehicleMileageExtended", new object[] {
                        Plate,
                        LocTime,
                        UserName,
                        Password,
                        ShowMileageInMeters}, this.GetVehicleMileageExtendedOperationCompleted, userState);
        }
        
        private void OnGetVehicleMileageExtendedOperationCompleted(object arg) {
            if ((this.GetVehicleMileageExtendedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetVehicleMileageExtendedCompleted(this, new GetVehicleMileageExtendedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetAllVehicleMileage", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceAllDataMileage GetAllVehicleMileage(string LocTime, string UserName, string Password, string ShowMileageInMeters) {
            object[] results = this.Invoke("GetAllVehicleMileage", new object[] {
                        LocTime,
                        UserName,
                        Password,
                        ShowMileageInMeters});
            return ((ServiceAllDataMileage)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllVehicleMileageAsync(string LocTime, string UserName, string Password, string ShowMileageInMeters) {
            this.GetAllVehicleMileageAsync(LocTime, UserName, Password, ShowMileageInMeters, null);
        }
        
        /// <remarks/>
        public void GetAllVehicleMileageAsync(string LocTime, string UserName, string Password, string ShowMileageInMeters, object userState) {
            if ((this.GetAllVehicleMileageOperationCompleted == null)) {
                this.GetAllVehicleMileageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllVehicleMileageOperationCompleted);
            }
            this.InvokeAsync("GetAllVehicleMileage", new object[] {
                        LocTime,
                        UserName,
                        Password,
                        ShowMileageInMeters}, this.GetAllVehicleMileageOperationCompleted, userState);
        }
        
        private void OnGetAllVehicleMileageOperationCompleted(object arg) {
            if ((this.GetAllVehicleMileageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllVehicleMileageCompleted(this, new GetAllVehicleMileageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/UpdateVehicleTripRoute_BCity", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IturanTripService UpdateVehicleTripRoute_BCity(
                    string ItemId, 
                    string TripId, 
                    string StartDate, 
                    string EndDate, 
                    string RouteAccountId, 
                    string RouteId, 
                    string RouteFullName, 
                    string RouteDescription, 
                    string VNumber, 
                    string DriverId, 
                    string Mode, 
                    string Netivim_WorkOrderNumber, 
                    string CompanyName, 
                    string DriverCellPhone, 
                    string DriverIdString, 
                    string UserName, 
                    string Password) {
            object[] results = this.Invoke("UpdateVehicleTripRoute_BCity", new object[] {
                        ItemId,
                        TripId,
                        StartDate,
                        EndDate,
                        RouteAccountId,
                        RouteId,
                        RouteFullName,
                        RouteDescription,
                        VNumber,
                        DriverId,
                        Mode,
                        Netivim_WorkOrderNumber,
                        CompanyName,
                        DriverCellPhone,
                        DriverIdString,
                        UserName,
                        Password});
            return ((IturanTripService)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateVehicleTripRoute_BCityAsync(
                    string ItemId, 
                    string TripId, 
                    string StartDate, 
                    string EndDate, 
                    string RouteAccountId, 
                    string RouteId, 
                    string RouteFullName, 
                    string RouteDescription, 
                    string VNumber, 
                    string DriverId, 
                    string Mode, 
                    string Netivim_WorkOrderNumber, 
                    string CompanyName, 
                    string DriverCellPhone, 
                    string DriverIdString, 
                    string UserName, 
                    string Password) {
            this.UpdateVehicleTripRoute_BCityAsync(ItemId, TripId, StartDate, EndDate, RouteAccountId, RouteId, RouteFullName, RouteDescription, VNumber, DriverId, Mode, Netivim_WorkOrderNumber, CompanyName, DriverCellPhone, DriverIdString, UserName, Password, null);
        }
        
        /// <remarks/>
        public void UpdateVehicleTripRoute_BCityAsync(
                    string ItemId, 
                    string TripId, 
                    string StartDate, 
                    string EndDate, 
                    string RouteAccountId, 
                    string RouteId, 
                    string RouteFullName, 
                    string RouteDescription, 
                    string VNumber, 
                    string DriverId, 
                    string Mode, 
                    string Netivim_WorkOrderNumber, 
                    string CompanyName, 
                    string DriverCellPhone, 
                    string DriverIdString, 
                    string UserName, 
                    string Password, 
                    object userState) {
            if ((this.UpdateVehicleTripRoute_BCityOperationCompleted == null)) {
                this.UpdateVehicleTripRoute_BCityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateVehicleTripRoute_BCityOperationCompleted);
            }
            this.InvokeAsync("UpdateVehicleTripRoute_BCity", new object[] {
                        ItemId,
                        TripId,
                        StartDate,
                        EndDate,
                        RouteAccountId,
                        RouteId,
                        RouteFullName,
                        RouteDescription,
                        VNumber,
                        DriverId,
                        Mode,
                        Netivim_WorkOrderNumber,
                        CompanyName,
                        DriverCellPhone,
                        DriverIdString,
                        UserName,
                        Password}, this.UpdateVehicleTripRoute_BCityOperationCompleted, userState);
        }
        
        private void OnUpdateVehicleTripRoute_BCityOperationCompleted(object arg) {
            if ((this.UpdateVehicleTripRoute_BCityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateVehicleTripRoute_BCityCompleted(this, new UpdateVehicleTripRoute_BCityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/UpdateVehicleTripRoute", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IturanTripService UpdateVehicleTripRoute(string ItemId, string TripId, string StartDate, string EndDate, string RouteAccountId, string RouteId, string RouteFullName, string RouteDescription, string VNumber, string DriverId, string Mode, string UserName, string Password) {
            object[] results = this.Invoke("UpdateVehicleTripRoute", new object[] {
                        ItemId,
                        TripId,
                        StartDate,
                        EndDate,
                        RouteAccountId,
                        RouteId,
                        RouteFullName,
                        RouteDescription,
                        VNumber,
                        DriverId,
                        Mode,
                        UserName,
                        Password});
            return ((IturanTripService)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateVehicleTripRouteAsync(string ItemId, string TripId, string StartDate, string EndDate, string RouteAccountId, string RouteId, string RouteFullName, string RouteDescription, string VNumber, string DriverId, string Mode, string UserName, string Password) {
            this.UpdateVehicleTripRouteAsync(ItemId, TripId, StartDate, EndDate, RouteAccountId, RouteId, RouteFullName, RouteDescription, VNumber, DriverId, Mode, UserName, Password, null);
        }
        
        /// <remarks/>
        public void UpdateVehicleTripRouteAsync(string ItemId, string TripId, string StartDate, string EndDate, string RouteAccountId, string RouteId, string RouteFullName, string RouteDescription, string VNumber, string DriverId, string Mode, string UserName, string Password, object userState) {
            if ((this.UpdateVehicleTripRouteOperationCompleted == null)) {
                this.UpdateVehicleTripRouteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateVehicleTripRouteOperationCompleted);
            }
            this.InvokeAsync("UpdateVehicleTripRoute", new object[] {
                        ItemId,
                        TripId,
                        StartDate,
                        EndDate,
                        RouteAccountId,
                        RouteId,
                        RouteFullName,
                        RouteDescription,
                        VNumber,
                        DriverId,
                        Mode,
                        UserName,
                        Password}, this.UpdateVehicleTripRouteOperationCompleted, userState);
        }
        
        private void OnUpdateVehicleTripRouteOperationCompleted(object arg) {
            if ((this.UpdateVehicleTripRouteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateVehicleTripRouteCompleted(this, new UpdateVehicleTripRouteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/Wakeup", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Wakeup() {
            this.Invoke("Wakeup", new object[0]);
        }
        
        /// <remarks/>
        public void WakeupAsync() {
            this.WakeupAsync(null);
        }
        
        /// <remarks/>
        public void WakeupAsync(object userState) {
            if ((this.WakeupOperationCompleted == null)) {
                this.WakeupOperationCompleted = new System.Threading.SendOrPostCallback(this.OnWakeupOperationCompleted);
            }
            this.InvokeAsync("Wakeup", new object[0], this.WakeupOperationCompleted, userState);
        }
        
        private void OnWakeupOperationCompleted(object arg) {
            if ((this.WakeupCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WakeupCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/SetDebugMode", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceDebugMode SetDebugMode(string mode) {
            object[] results = this.Invoke("SetDebugMode", new object[] {
                        mode});
            return ((ServiceDebugMode)(results[0]));
        }
        
        /// <remarks/>
        public void SetDebugModeAsync(string mode) {
            this.SetDebugModeAsync(mode, null);
        }
        
        /// <remarks/>
        public void SetDebugModeAsync(string mode, object userState) {
            if ((this.SetDebugModeOperationCompleted == null)) {
                this.SetDebugModeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetDebugModeOperationCompleted);
            }
            this.InvokeAsync("SetDebugMode", new object[] {
                        mode}, this.SetDebugModeOperationCompleted, userState);
        }
        
        private void OnSetDebugModeOperationCompleted(object arg) {
            if ((this.SetDebugModeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetDebugModeCompleted(this, new SetDebugModeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetPlatformDataExtenteded", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServicePlatformData GetPlatformDataExtenteded(string Plate, string UserName, string Password, string ShowAreas, string ShowStatuses, string ShowMileageInMeters, string ShowDriver) {
            object[] results = this.Invoke("GetPlatformDataExtenteded", new object[] {
                        Plate,
                        UserName,
                        Password,
                        ShowAreas,
                        ShowStatuses,
                        ShowMileageInMeters,
                        ShowDriver});
            return ((ServicePlatformData)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlatformDataExtentededAsync(string Plate, string UserName, string Password, string ShowAreas, string ShowStatuses, string ShowMileageInMeters, string ShowDriver) {
            this.GetPlatformDataExtentededAsync(Plate, UserName, Password, ShowAreas, ShowStatuses, ShowMileageInMeters, ShowDriver, null);
        }
        
        /// <remarks/>
        public void GetPlatformDataExtentededAsync(string Plate, string UserName, string Password, string ShowAreas, string ShowStatuses, string ShowMileageInMeters, string ShowDriver, object userState) {
            if ((this.GetPlatformDataExtentededOperationCompleted == null)) {
                this.GetPlatformDataExtentededOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlatformDataExtentededOperationCompleted);
            }
            this.InvokeAsync("GetPlatformDataExtenteded", new object[] {
                        Plate,
                        UserName,
                        Password,
                        ShowAreas,
                        ShowStatuses,
                        ShowMileageInMeters,
                        ShowDriver}, this.GetPlatformDataExtentededOperationCompleted, userState);
        }
        
        private void OnGetPlatformDataExtentededOperationCompleted(object arg) {
            if ((this.GetPlatformDataExtentededCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlatformDataExtentededCompleted(this, new GetPlatformDataExtentededCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetPlatformData", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServicePlatformData GetPlatformData(string Plate, string UserName, string Password, string ShowAreas, string ShowStatuses) {
            object[] results = this.Invoke("GetPlatformData", new object[] {
                        Plate,
                        UserName,
                        Password,
                        ShowAreas,
                        ShowStatuses});
            return ((ServicePlatformData)(results[0]));
        }
        
        /// <remarks/>
        public void GetPlatformDataAsync(string Plate, string UserName, string Password, string ShowAreas, string ShowStatuses) {
            this.GetPlatformDataAsync(Plate, UserName, Password, ShowAreas, ShowStatuses, null);
        }
        
        /// <remarks/>
        public void GetPlatformDataAsync(string Plate, string UserName, string Password, string ShowAreas, string ShowStatuses, object userState) {
            if ((this.GetPlatformDataOperationCompleted == null)) {
                this.GetPlatformDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPlatformDataOperationCompleted);
            }
            this.InvokeAsync("GetPlatformData", new object[] {
                        Plate,
                        UserName,
                        Password,
                        ShowAreas,
                        ShowStatuses}, this.GetPlatformDataOperationCompleted, userState);
        }
        
        private void OnGetPlatformDataOperationCompleted(object arg) {
            if ((this.GetPlatformDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPlatformDataCompleted(this, new GetPlatformDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetAllPlatformsDataShortened", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceAllPlatformDataShortened GetAllPlatformsDataShortened(string UserName, string Password) {
            object[] results = this.Invoke("GetAllPlatformsDataShortened", new object[] {
                        UserName,
                        Password});
            return ((ServiceAllPlatformDataShortened)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPlatformsDataShortenedAsync(string UserName, string Password) {
            this.GetAllPlatformsDataShortenedAsync(UserName, Password, null);
        }
        
        /// <remarks/>
        public void GetAllPlatformsDataShortenedAsync(string UserName, string Password, object userState) {
            if ((this.GetAllPlatformsDataShortenedOperationCompleted == null)) {
                this.GetAllPlatformsDataShortenedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPlatformsDataShortenedOperationCompleted);
            }
            this.InvokeAsync("GetAllPlatformsDataShortened", new object[] {
                        UserName,
                        Password}, this.GetAllPlatformsDataShortenedOperationCompleted, userState);
        }
        
        private void OnGetAllPlatformsDataShortenedOperationCompleted(object arg) {
            if ((this.GetAllPlatformsDataShortenedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPlatformsDataShortenedCompleted(this, new GetAllPlatformsDataShortenedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/GetAllPlatformsData", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ServiceAllPlatformData GetAllPlatformsData(string UserName, string Password, string ShowAreas, string ShowStatuses, string ShowMileageInMeters, string ShowDriver) {
            object[] results = this.Invoke("GetAllPlatformsData", new object[] {
                        UserName,
                        Password,
                        ShowAreas,
                        ShowStatuses,
                        ShowMileageInMeters,
                        ShowDriver});
            return ((ServiceAllPlatformData)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllPlatformsDataAsync(string UserName, string Password, string ShowAreas, string ShowStatuses, string ShowMileageInMeters, string ShowDriver) {
            this.GetAllPlatformsDataAsync(UserName, Password, ShowAreas, ShowStatuses, ShowMileageInMeters, ShowDriver, null);
        }
        
        /// <remarks/>
        public void GetAllPlatformsDataAsync(string UserName, string Password, string ShowAreas, string ShowStatuses, string ShowMileageInMeters, string ShowDriver, object userState) {
            if ((this.GetAllPlatformsDataOperationCompleted == null)) {
                this.GetAllPlatformsDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPlatformsDataOperationCompleted);
            }
            this.InvokeAsync("GetAllPlatformsData", new object[] {
                        UserName,
                        Password,
                        ShowAreas,
                        ShowStatuses,
                        ShowMileageInMeters,
                        ShowDriver}, this.GetAllPlatformsDataOperationCompleted, userState);
        }
        
        private void OnGetAllPlatformsDataOperationCompleted(object arg) {
            if ((this.GetAllPlatformsDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllPlatformsDataCompleted(this, new GetAllPlatformsDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/SendUpdateKeyboardPassword", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CommandResult SendUpdateKeyboardPassword(string UserName, string Password, string Plate, string KeyboardPassword) {
            object[] results = this.Invoke("SendUpdateKeyboardPassword", new object[] {
                        UserName,
                        Password,
                        Plate,
                        KeyboardPassword});
            return ((CommandResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendUpdateKeyboardPasswordAsync(string UserName, string Password, string Plate, string KeyboardPassword) {
            this.SendUpdateKeyboardPasswordAsync(UserName, Password, Plate, KeyboardPassword, null);
        }
        
        /// <remarks/>
        public void SendUpdateKeyboardPasswordAsync(string UserName, string Password, string Plate, string KeyboardPassword, object userState) {
            if ((this.SendUpdateKeyboardPasswordOperationCompleted == null)) {
                this.SendUpdateKeyboardPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUpdateKeyboardPasswordOperationCompleted);
            }
            this.InvokeAsync("SendUpdateKeyboardPassword", new object[] {
                        UserName,
                        Password,
                        Plate,
                        KeyboardPassword}, this.SendUpdateKeyboardPasswordOperationCompleted, userState);
        }
        
        private void OnSendUpdateKeyboardPasswordOperationCompleted(object arg) {
            if ((this.SendUpdateKeyboardPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUpdateKeyboardPasswordCompleted(this, new SendUpdateKeyboardPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/SendUpdateOdometer", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CommandResult SendUpdateOdometer(string UserName, string Password, string Plate, int Odometor) {
            object[] results = this.Invoke("SendUpdateOdometer", new object[] {
                        UserName,
                        Password,
                        Plate,
                        Odometor});
            return ((CommandResult)(results[0]));
        }
        
        /// <remarks/>
        public void SendUpdateOdometerAsync(string UserName, string Password, string Plate, int Odometor) {
            this.SendUpdateOdometerAsync(UserName, Password, Plate, Odometor, null);
        }
        
        /// <remarks/>
        public void SendUpdateOdometerAsync(string UserName, string Password, string Plate, int Odometor, object userState) {
            if ((this.SendUpdateOdometerOperationCompleted == null)) {
                this.SendUpdateOdometerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUpdateOdometerOperationCompleted);
            }
            this.InvokeAsync("SendUpdateOdometer", new object[] {
                        UserName,
                        Password,
                        Plate,
                        Odometor}, this.SendUpdateOdometerOperationCompleted, userState);
        }
        
        private void OnSendUpdateOdometerOperationCompleted(object arg) {
            if ((this.SendUpdateOdometerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUpdateOdometerCompleted(this, new SendUpdateOdometerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/CheckCommandResult", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckCommandResult(string UserName, string Password, string GUID) {
            object[] results = this.Invoke("CheckCommandResult", new object[] {
                        UserName,
                        Password,
                        GUID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckCommandResultAsync(string UserName, string Password, string GUID) {
            this.CheckCommandResultAsync(UserName, Password, GUID, null);
        }
        
        /// <remarks/>
        public void CheckCommandResultAsync(string UserName, string Password, string GUID, object userState) {
            if ((this.CheckCommandResultOperationCompleted == null)) {
                this.CheckCommandResultOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckCommandResultOperationCompleted);
            }
            this.InvokeAsync("CheckCommandResult", new object[] {
                        UserName,
                        Password,
                        GUID}, this.CheckCommandResultOperationCompleted, userState);
        }
        
        private void OnCheckCommandResultOperationCompleted(object arg) {
            if ((this.CheckCommandResultCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckCommandResultCompleted(this, new CheckCommandResultCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/RevGeoCoding", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RevGeoCodingData RevGeoCoding(double latitude, double longitude, string Password) {
            object[] results = this.Invoke("RevGeoCoding", new object[] {
                        latitude,
                        longitude,
                        Password});
            return ((RevGeoCodingData)(results[0]));
        }
        
        /// <remarks/>
        public void RevGeoCodingAsync(double latitude, double longitude, string Password) {
            this.RevGeoCodingAsync(latitude, longitude, Password, null);
        }
        
        /// <remarks/>
        public void RevGeoCodingAsync(double latitude, double longitude, string Password, object userState) {
            if ((this.RevGeoCodingOperationCompleted == null)) {
                this.RevGeoCodingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRevGeoCodingOperationCompleted);
            }
            this.InvokeAsync("RevGeoCoding", new object[] {
                        latitude,
                        longitude,
                        Password}, this.RevGeoCodingOperationCompleted, userState);
        }
        
        private void OnRevGeoCodingOperationCompleted(object arg) {
            if ((this.RevGeoCodingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RevGeoCodingCompleted(this, new RevGeoCodingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.ituran.com/ituranWebService3/RevGeoCodingExact", RequestNamespace="http://www.ituran.com/ituranWebService3", ResponseNamespace="http://www.ituran.com/ituranWebService3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AddressData RevGeoCodingExact(double latitude, double longitude) {
            object[] results = this.Invoke("RevGeoCodingExact", new object[] {
                        latitude,
                        longitude});
            return ((AddressData)(results[0]));
        }
        
        /// <remarks/>
        public void RevGeoCodingExactAsync(double latitude, double longitude) {
            this.RevGeoCodingExactAsync(latitude, longitude, null);
        }
        
        /// <remarks/>
        public void RevGeoCodingExactAsync(double latitude, double longitude, object userState) {
            if ((this.RevGeoCodingExactOperationCompleted == null)) {
                this.RevGeoCodingExactOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRevGeoCodingExactOperationCompleted);
            }
            this.InvokeAsync("RevGeoCodingExact", new object[] {
                        latitude,
                        longitude}, this.RevGeoCodingExactOperationCompleted, userState);
        }
        
        private void OnRevGeoCodingExactOperationCompleted(object arg) {
            if ((this.RevGeoCodingExactCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RevGeoCodingExactCompleted(this, new RevGeoCodingExactCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class VehiceMileage {
        
        private string resultCodeField;
        
        private System.DateTime resLocTimeField;
        
        private double resMileageField;
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime resLocTime {
            get {
                return this.resLocTimeField;
            }
            set {
                this.resLocTimeField = value;
            }
        }
        
        /// <remarks/>
        public double resMileage {
            get {
                return this.resMileageField;
            }
            set {
                this.resMileageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class AddressData {
        
        private string returnCodeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string addressField;
        
        private string countryField;
        
        private string countryCodeField;
        
        private string stateField;
        
        private string countyField;
        
        private string cityField;
        
        private string streetField;
        
        private int houseNumberField;
        
        private int accuracyField;
        
        private int roadClassField;
        
        private int speedLimitField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public int HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Accuracy {
            get {
                return this.accuracyField;
            }
            set {
                this.accuracyField = value;
            }
        }
        
        /// <remarks/>
        public int RoadClass {
            get {
                return this.roadClassField;
            }
            set {
                this.roadClassField = value;
            }
        }
        
        /// <remarks/>
        public int SpeedLimit {
            get {
                return this.speedLimitField;
            }
            set {
                this.speedLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class RevGeoCodingData {
        
        private string returnCodeField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string addressField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class CommandResult {
        
        private string errorField;
        
        private string[] gUIDsField;
        
        private string[] unitsField;
        
        private string[] gUID_errorsField;
        
        /// <remarks/>
        public string Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        public string[] GUIDs {
            get {
                return this.gUIDsField;
            }
            set {
                this.gUIDsField = value;
            }
        }
        
        /// <remarks/>
        public string[] Units {
            get {
                return this.unitsField;
            }
            set {
                this.unitsField = value;
            }
        }
        
        /// <remarks/>
        public string[] GUID_errors {
            get {
                return this.gUID_errorsField;
            }
            set {
                this.gUID_errorsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class ServiceAllPlatformData {
        
        private string returnCodeField;
        
        private string usernameField;
        
        private ServicePlatformData[] vehListField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public ServicePlatformData[] VehList {
            get {
                return this.vehListField;
            }
            set {
                this.vehListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class ServicePlatformData {
        
        private string returnCodeField;
        
        private string plateField;
        
        private string vINField;
        
        private System.DateTime lastLocationTimeField;
        
        private double lastLatitudeField;
        
        private double lastLongitudeField;
        
        private int lastSpeedField;
        
        private int lastHeadField;
        
        private double lastMilieageField;
        
        private string lastAddressField;
        
        private long uAIDField;
        
        private string[] areasField;
        
        private string[] statusesField;
        
        private string usernameField;
        
        private string drivernameField;
        
        private string driverTZField;
        
        private TempSensorMinData[] temperatureSensorsField;
        
        private int currentDriverIdField;
        
        private string labelField;
        
        private int platfromIdField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Plate {
            get {
                return this.plateField;
            }
            set {
                this.plateField = value;
            }
        }
        
        /// <remarks/>
        public string VIN {
            get {
                return this.vINField;
            }
            set {
                this.vINField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastLocationTime {
            get {
                return this.lastLocationTimeField;
            }
            set {
                this.lastLocationTimeField = value;
            }
        }
        
        /// <remarks/>
        public double LastLatitude {
            get {
                return this.lastLatitudeField;
            }
            set {
                this.lastLatitudeField = value;
            }
        }
        
        /// <remarks/>
        public double LastLongitude {
            get {
                return this.lastLongitudeField;
            }
            set {
                this.lastLongitudeField = value;
            }
        }
        
        /// <remarks/>
        public int LastSpeed {
            get {
                return this.lastSpeedField;
            }
            set {
                this.lastSpeedField = value;
            }
        }
        
        /// <remarks/>
        public int LastHead {
            get {
                return this.lastHeadField;
            }
            set {
                this.lastHeadField = value;
            }
        }
        
        /// <remarks/>
        public double LastMilieage {
            get {
                return this.lastMilieageField;
            }
            set {
                this.lastMilieageField = value;
            }
        }
        
        /// <remarks/>
        public string LastAddress {
            get {
                return this.lastAddressField;
            }
            set {
                this.lastAddressField = value;
            }
        }
        
        /// <remarks/>
        public long UAID {
            get {
                return this.uAIDField;
            }
            set {
                this.uAIDField = value;
            }
        }
        
        /// <remarks/>
        public string[] areas {
            get {
                return this.areasField;
            }
            set {
                this.areasField = value;
            }
        }
        
        /// <remarks/>
        public string[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string drivername {
            get {
                return this.drivernameField;
            }
            set {
                this.drivernameField = value;
            }
        }
        
        /// <remarks/>
        public string DriverTZ {
            get {
                return this.driverTZField;
            }
            set {
                this.driverTZField = value;
            }
        }
        
        /// <remarks/>
        public TempSensorMinData[] TemperatureSensors {
            get {
                return this.temperatureSensorsField;
            }
            set {
                this.temperatureSensorsField = value;
            }
        }
        
        /// <remarks/>
        public int currentDriverId {
            get {
                return this.currentDriverIdField;
            }
            set {
                this.currentDriverIdField = value;
            }
        }
        
        /// <remarks/>
        public string Label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public int PlatfromId {
            get {
                return this.platfromIdField;
            }
            set {
                this.platfromIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class TempSensorMinData {
        
        private string lastTemperatureField;
        
        private string temperatureTimeField;
        
        private string nameField;
        
        private int sensor1to4Field;
        
        /// <remarks/>
        public string LastTemperature {
            get {
                return this.lastTemperatureField;
            }
            set {
                this.lastTemperatureField = value;
            }
        }
        
        /// <remarks/>
        public string TemperatureTime {
            get {
                return this.temperatureTimeField;
            }
            set {
                this.temperatureTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int Sensor1to4 {
            get {
                return this.sensor1to4Field;
            }
            set {
                this.sensor1to4Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class ServicePlatformDataShortened {
        
        private int platformIdField;
        
        private string lastLocationTimeField;
        
        private double lastLatitudeField;
        
        private double lastLongitudeField;
        
        private int lastSpeedField;
        
        private int lastHeadField;
        
        private string[] statusesField;
        
        /// <remarks/>
        public int PlatformId {
            get {
                return this.platformIdField;
            }
            set {
                this.platformIdField = value;
            }
        }
        
        /// <remarks/>
        public string LastLocationTime {
            get {
                return this.lastLocationTimeField;
            }
            set {
                this.lastLocationTimeField = value;
            }
        }
        
        /// <remarks/>
        public double LastLatitude {
            get {
                return this.lastLatitudeField;
            }
            set {
                this.lastLatitudeField = value;
            }
        }
        
        /// <remarks/>
        public double LastLongitude {
            get {
                return this.lastLongitudeField;
            }
            set {
                this.lastLongitudeField = value;
            }
        }
        
        /// <remarks/>
        public int LastSpeed {
            get {
                return this.lastSpeedField;
            }
            set {
                this.lastSpeedField = value;
            }
        }
        
        /// <remarks/>
        public int LastHead {
            get {
                return this.lastHeadField;
            }
            set {
                this.lastHeadField = value;
            }
        }
        
        /// <remarks/>
        public string[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class ServiceAllPlatformDataShortened {
        
        private string returnCodeField;
        
        private string usernameField;
        
        private ServicePlatformDataShortened[] vehListField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public ServicePlatformDataShortened[] VehList {
            get {
                return this.vehListField;
            }
            set {
                this.vehListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class ServiceDebugMode {
        
        private string debugModeField;
        
        /// <remarks/>
        public string DebugMode {
            get {
                return this.debugModeField;
            }
            set {
                this.debugModeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class IturanTripService {
        
        private string resultCodeField;
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class VehiceMileageExt {
        
        private string resultCodeField;
        
        private System.DateTime resLocTimeField;
        
        private double resMileageField;
        
        private string plateField;
        
        /// <remarks/>
        public string ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime resLocTime {
            get {
                return this.resLocTimeField;
            }
            set {
                this.resLocTimeField = value;
            }
        }
        
        /// <remarks/>
        public double resMileage {
            get {
                return this.resMileageField;
            }
            set {
                this.resMileageField = value;
            }
        }
        
        /// <remarks/>
        public string Plate {
            get {
                return this.plateField;
            }
            set {
                this.plateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ituran.com/ituranWebService3")]
    public partial class ServiceAllDataMileage {
        
        private string returnCodeField;
        
        private string messageField;
        
        private string usernameField;
        
        private VehiceMileageExt[] vehListField;
        
        /// <remarks/>
        public string ReturnCode {
            get {
                return this.returnCodeField;
            }
            set {
                this.returnCodeField = value;
            }
        }
        
        /// <remarks/>
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public VehiceMileageExt[] VehList {
            get {
                return this.vehListField;
            }
            set {
                this.vehListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetVehicleMileageCompletedEventHandler(object sender, GetVehicleMileageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVehicleMileageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVehicleMileageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VehiceMileage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VehiceMileage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetVehicleMileageExtendedCompletedEventHandler(object sender, GetVehicleMileageExtendedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetVehicleMileageExtendedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetVehicleMileageExtendedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VehiceMileage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VehiceMileage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAllVehicleMileageCompletedEventHandler(object sender, GetAllVehicleMileageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllVehicleMileageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllVehicleMileageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceAllDataMileage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceAllDataMileage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpdateVehicleTripRoute_BCityCompletedEventHandler(object sender, UpdateVehicleTripRoute_BCityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateVehicleTripRoute_BCityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateVehicleTripRoute_BCityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IturanTripService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IturanTripService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void UpdateVehicleTripRouteCompletedEventHandler(object sender, UpdateVehicleTripRouteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateVehicleTripRouteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateVehicleTripRouteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IturanTripService Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IturanTripService)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void WakeupCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SetDebugModeCompletedEventHandler(object sender, SetDebugModeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetDebugModeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetDebugModeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceDebugMode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceDebugMode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetPlatformDataExtentededCompletedEventHandler(object sender, GetPlatformDataExtentededCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlatformDataExtentededCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlatformDataExtentededCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicePlatformData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicePlatformData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetPlatformDataCompletedEventHandler(object sender, GetPlatformDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPlatformDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPlatformDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServicePlatformData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServicePlatformData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAllPlatformsDataShortenedCompletedEventHandler(object sender, GetAllPlatformsDataShortenedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPlatformsDataShortenedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPlatformsDataShortenedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceAllPlatformDataShortened Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceAllPlatformDataShortened)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void GetAllPlatformsDataCompletedEventHandler(object sender, GetAllPlatformsDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllPlatformsDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllPlatformsDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceAllPlatformData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceAllPlatformData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SendUpdateKeyboardPasswordCompletedEventHandler(object sender, SendUpdateKeyboardPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUpdateKeyboardPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUpdateKeyboardPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommandResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommandResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void SendUpdateOdometerCompletedEventHandler(object sender, SendUpdateOdometerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUpdateOdometerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUpdateOdometerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CommandResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CommandResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void CheckCommandResultCompletedEventHandler(object sender, CheckCommandResultCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckCommandResultCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckCommandResultCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void RevGeoCodingCompletedEventHandler(object sender, RevGeoCodingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RevGeoCodingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RevGeoCodingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RevGeoCodingData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RevGeoCodingData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void RevGeoCodingExactCompletedEventHandler(object sender, RevGeoCodingExactCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RevGeoCodingExactCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RevGeoCodingExactCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AddressData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AddressData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591